### ISSUE TITLE
No way to swap cameras

### ISSUE THREAD

**Issue by edent** [TimDaub/scan.lol#3]
My Android phone has two cameras - front and rear. Sometimes, the app opens the front camera and all I can see is my face. Is there a way to swap between the cameras?

**Comment by TimDaub** [comment]
👋🏼  thanks for pointing that out, and no, that functionality doesn't exist yet.

I think I'd be nice to have it though. Similar to the camera swap button of a photo app.

**Comment by TimDaub** [comment]
> Sometimes, the app opens the front camera and all I can see is my face.

This should be fixed in a484a465ff044638153af1c3a3e655a0e1fd384a
